title: Susmitha Kunadharaju
logo: https://raw.githubusercontent.com/susmithakun/SusmithaKunadharaju-github.io/main/assets/img/MyPhoto.png
#description: text below image
Github: ![GitHub](https://i.stack.imgur.com/tskMh.png)
#show_downloads: false
theme: jekyll-theme-minimal
