title: Susmitha Kunadharaju
logo: https://raw.githubusercontent.com/susmithakun/SusmithaKunadharaju-github.io/main/assets/img/MyPhoto.png
<a href="https://www.linkedin.com/in/susmithakunadharaju/">
<img src="https://img.shields.io/badge/Linkedin-0077B5?style=flat-square&logo=Linkedin&logoColor=ffffff"></a>
<a href="https://github.com/susmithakun/">
<img src="https://img.shields.io/badge/Github-211F1F?style=flat-square&logo=GitHub&logoColor=ffffff"></a> 
#description: text below image
#show_downloads: false
theme: jekyll-theme-minimal
